---
changelog:
  categories:
    - title: Backwards-incompatible protocol changes
      labels:
        - protocol-incompat
    - title: Protocol changes
      labels:
        - protocol
    - title: Other changes
      labels:
        - "*"
