---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# See https://github.com/github/super-linter/blob/main/TEMPLATES/.markdown-lint.yml for an example
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############

# MD013/line-length - Line length
#  MD013:
#    # Number of characters
#    line_length: 1000

#################
# Rules by tags #
#################

# MD041/first-line-heading/first-line-h1
# First line in a file being a top-level heading collides with starting
# each file with a copyright statement.
first-line-h1: false # Affects 45 files

# MD013/line-length - Line length
line-length:
    line_length: 900 # Arbitrary length to catch the worst. Setting this to 120 affects 500 lines

# MD022/blanks-around-headings/blanks-around-headers - Headings should be surrounded by blank lines
blanks-around-headings: false # Affects 460 lines

# MD033/no-inline-html - Inline HTML
no-inline-html: false # Used by: usage-examples/build-avoidance.md, eiffel-syntax-and-usage/the-meta-object.md, README.md
